### ISSUE TITLE
ModuleNotFoundError: No module named 'mkdocs.tests'

### ISSUE THREAD

**Issue by maurosilber** [conda-forge/mkdocs-jupyter-feedstock#31] opened 2024-05-11 22:36 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi!

There seems to be some differences between this version and the PyPI one.

Some days ago, it seemed to be missing some jupyter assets (some .css files, but I cannot remember the paths now).

Now, I recreated an environment from scratch:

```yaml
# environment.yaml
name: labo1
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - scipy
  - pytest
  - mkdocs-material
  - mkdocstrings-python
  - mkdocs-jupyter
 ```

and get the following error:

```python-traceback
File ".../lib/python3.12/site-packages/mkdocs_jupyter/plugin.py", line 9, in <module>
    from mkdocs.tests.base import get_markdown_toc
ModuleNotFoundError: No module named 'mkdocs.tests'
```

But it works fine if I uninstall and reinstall `mkdocs-jupyter` from `PyPI`.

Let me know if I can help somehow to fix this.

Thanks!
Mauro

### Installed packages

```shell
# Name                    Version                   Build  Channel
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hb547adb_1    conda-forge
brotli-bin                1.1.0                hb547adb_1    conda-forge
brotli-python             1.1.0           py312h9f69965_1    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2024.2.2             hf0a4a13_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h0fef576_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
fonttools                 4.51.0          py312he37b823_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
ghp-import                2.1.0              pyhd8ed1ab_0    conda-forge
griffe                    0.44.0             pyhd8ed1ab_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsonschema                4.22.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312h81bd7bf_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupytext                  1.16.2             pyhd8ed1ab_1    conda-forge
kiwisolver                1.4.5           py312h389731b_1    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
labo1                     1.0.1.dev0+g3efc96c.d20240511          pypi_0    pypi
lcms2                     2.16                 ha0e7c42_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           22_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hb547adb_1    conda-forge
libbrotlidec              1.1.0                hb547adb_1    conda-forge
libbrotlienc              1.1.0                hb547adb_1    conda-forge
libcblas                  3.9.0           22_osxarm64_openblas    conda-forge
libcxx                    17.0.6               h5f092b4_0    conda-forge
libdeflate                1.20                 h93a5062_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libexpat                  2.6.2                hebf3989_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           22_osxarm64_openblas    conda-forge
libopenblas               0.3.27          openmp_h6c19121_0    conda-forge
libpng                    1.6.43               h091b4b1_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.45.3               h091b4b1_0    conda-forge
libtiff                   4.6.0                h07db509_3    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               18.1.5               hde57baf_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py312he37b823_0    conda-forge
matplotlib                3.8.4           py312h1f38498_0    conda-forge
matplotlib-base           3.8.4           py312ha6faf65_0    conda-forge
mdit-py-plugins           0.4.0              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mergedeep                 1.3.4              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkdocs                    1.6.0              pyhd8ed1ab_0    conda-forge
mkdocs-autorefs           1.0.1              pyhd8ed1ab_0    conda-forge
mkdocs-get-deps           0.2.0              pyhd8ed1ab_0    conda-forge
mkdocs-jupyter            0.24.6             pyhd8ed1ab_0    conda-forge
mkdocs-material           9.5.21             pyhd8ed1ab_0    conda-forge
mkdocs-material-extensions 1.3.1              pyhd8ed1ab_0    conda-forge
mkdocstrings              0.25.1             pyhd8ed1ab_0    conda-forge
mkdocstrings-python       1.10.0             pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.4               hd8ed1ab_0    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.16.4               hd8ed1ab_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  hb89a1cb_0    conda-forge
numpy                     1.26.4          py312h8442bc7_0    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.3.0                h0d3ecfb_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
paginate                  0.5.6              pyhd8ed1ab_0    conda-forge
pandoc                    3.1.13               hce30654_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
pillow                    10.3.0          py312h8a801b1_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pymdown-extensions        10.8.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    8.2.0              pyhd8ed1ab_0    conda-forge
python                    3.12.3          h4a7b5fc_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py312h02f2b3b_1    conda-forge
pyyaml-env-tag            0.1                pyhd8ed1ab_0    conda-forge
pyzmq                     26.0.3          py312hfa13136_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
regex                     2024.5.10       py312h7e5086c_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rpds-py                   0.18.1          py312h552d48e_0    conda-forge
scipy                     1.13.0          py312h14ffa8f_1    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4             py312he37b823_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
watchdog                  4.0.0           py312he37b823_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.5                h5119023_3    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

### Environment info

```shell
mamba version : 1.5.5
     active environment : labo1
    active env location : /Users/maurosilber/miniforge3/envs/labo1
            shell level : 1
       user config file : /Users/maurosilber/.condarc
 populated config files : /Users/maurosilber/miniforge3/.condarc
                          /Users/maurosilber/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m2
                          __conda=23.11.0=0
                          __osx=14.4.1=0
                          __unix=0=0
       base environment : /Users/maurosilber/miniforge3  (writable)
      conda av data dir : /Users/maurosilber/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/maurosilber/miniforge3/pkgs
                          /Users/maurosilber/.conda/pkgs
       envs directories : /Users/maurosilber/miniforge3/envs
                          /Users/maurosilber/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Darwin/23.4.0 OSX/14.4.1 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by cwognum** [comment] 2024-05-12 15:29
Hey @maurosilber, thanks for raising the issue. We are aware! 

- The `ModuleNotFoundError` is caused by an incompatibility between `mkdocs` and `mkdocs-jupyter` versions. The conda-forge version of `mkdocs-jupyter` is still at `0.24.6`, whereas on PyPi the latest is `0.24.7`.
  - Before I was a maintainer of this repo, I actually raised the same issue: https://github.com/conda-forge/mkdocs-jupyter-feedstock/pull/29#issuecomment-2086834906
  - This was caused by an issue in the upstream repo, see https://github.com/danielfrg/mkdocs-jupyter/issues/197
- The previous maintainer tried to fix this in https://github.com/conda-forge/mkdocs-jupyter-feedstock/pull/30, but unfortunately this led to another issue (the missing web assets you mentioned!). 
  - The package was thus labeled as broken: https://github.com/conda-forge/admin-requests/pull/982

It seems the upstream maintainer made a mistake in his release to PyPi, which he is planning to fix (see his comment [here](https://github.com/danielfrg/mkdocs-jupyter/issues/197#issuecomment-2098998170)). Because of that, I think it's best to wait for this upstream fix, rather than trying to patch the release process here.

**Comment by cwognum** [comment] 2024-07-03 15:52
Now that https://github.com/danielfrg/mkdocs-jupyter/issues/197 is closed, this should be fixed with https://github.com/conda-forge/mkdocs-jupyter-feedstock/pull/35! 

Make sure to install the latest build (`pyhd8ed1ab_1`). This should be done automatically be conda, but if you have the previous build for v0.24.8 cached locally, it may use that instead!

**Closed as completed by cwognum** 2024-07-03 15:52 UTC
Labels: bug
